/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Transaction = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'contiPayReference' : IDL.Opt(IDL.Text),
  'totalCharged' : IDL.Nat,
  'contiPayError' : IDL.Opt(IDL.Text),
  'amountUsd' : IDL.Nat,
  'timestampNanos' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateTotalCost' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'createOrUpdateApiCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Bool)],
      [],
      [],
    ),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'orchestratePayment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [Transaction],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'success' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'contiPayReference' : IDL.Opt(IDL.Text),
    'totalCharged' : IDL.Nat,
    'contiPayError' : IDL.Opt(IDL.Text),
    'amountUsd' : IDL.Nat,
    'timestampNanos' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateTotalCost' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'createOrUpdateApiCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Bool)],
        [],
        [],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'orchestratePayment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [Transaction],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };